# Generated by Django 2.0.3 on 2018-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_celery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('multiplier', models.IntegerField()),
                ('multiplicand', models.IntegerField()),
                ('log_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Add',
            new_name='Plus',
        ),
    ]
